doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
        #server_version: '16'
        use_savepoints: true
=======
        #server_version: '15'
>>>>>>> 81688ff31e36db63b702e05ba73f5478ffdd725f
=======
        #server_version: '16'
        use_savepoints: true
>>>>>>> 649ef9c620e35f87ee5e3746f7e798e948fc7cc4
=======
        #server_version: '15'
>>>>>>> 0f9be098c09a370d9b7246eec13ee77203b60875
=======
        #server_version: '15'
>>>>>>> eb00ab66c5c8cb0c2ad54f78e46097d1f33bb681
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    
=======
>>>>>>> 81688ff31e36db63b702e05ba73f5478ffdd725f
=======
>>>>>>> 649ef9c620e35f87ee5e3746f7e798e948fc7cc4
=======
>>>>>>> 0f9be098c09a370d9b7246eec13ee77203b60875
=======
>>>>>>> eb00ab66c5c8cb0c2ad54f78e46097d1f33bb681
