framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
<<<<<<< HEAD
<<<<<<< HEAD
        message_bus: false
=======
>>>>>>> 81688ff31e36db63b702e05ba73f5478ffdd725f
=======
        message_bus: false
>>>>>>> 649ef9c620e35f87ee5e3746f7e798e948fc7cc4
