framework:
<<<<<<< HEAD
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
<<<<<<< HEAD
        providers:
=======
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
>>>>>>> 81688ff31e36db63b702e05ba73f5478ffdd725f
=======
    translator:
        enabled: false
>>>>>>> 649ef9c620e35f87ee5e3746f7e798e948fc7cc4
