twig:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    default_path: '%kernel.project_dir%/templates'
<<<<<<< HEAD
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        app_environement: '%env(APP_ENV)%'
        stripe_public_key_test: '%env(STRIPE_PUBLIC_KEY_TEST)%'
when@test:
    twig:
        strict_variables: true
    
=======
=======
    default_path: '%kernel.project_dir%/templates'  
>>>>>>> 649ef9c620e35f87ee5e3746f7e798e948fc7cc4
=======
    default_path: '%kernel.project_dir%/templates'
>>>>>>> 0f9be098c09a370d9b7246eec13ee77203b60875
=======
    default_path: '%kernel.project_dir%/templates'
>>>>>>> eb00ab66c5c8cb0c2ad54f78e46097d1f33bb681

when@test:
    twig:
        strict_variables: true
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 81688ff31e36db63b702e05ba73f5478ffdd725f
=======

>>>>>>> 649ef9c620e35f87ee5e3746f7e798e948fc7cc4
=======
>>>>>>> 0f9be098c09a370d9b7246eec13ee77203b60875
=======
>>>>>>> eb00ab66c5c8cb0c2ad54f78e46097d1f33bb681
