<<<<<<< HEAD
<<<<<<< HEAD
version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###

=======
=======
>>>>>>> eb00ab66c5c8cb0c2ad54f78e46097d1f33bb681
version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
###< symfony/mailer ###
<<<<<<< HEAD
>>>>>>> 0f9be098c09a370d9b7246eec13ee77203b60875
=======
>>>>>>> eb00ab66c5c8cb0c2ad54f78e46097d1f33bb681
