# index:
#    path: /
#    controller: App\Controller\DefaultController::index
reclamation:
  resource: App\Controller\ReclamationController
  type: annotation

add_reclamation_page:
    path: '/addReclamationPage'
    controller: 'App\Controller\ReclamationController::addReclamationPage'

    


reclamationDetails:
    path: /reclamation/{id}/details
    controller: App\Controller\ReclamationController::reclamationDetails
    requirements:
        id: '\d+'


reclamation_details:
    path: /reclamation/{id}
    controller: App\Controller\ReclamationController::reclamationDetails


repondre:
    resource: 'App\Controller\RepondreController'
    type:     annotation


generate_pdf:
    path: /generate-pdf/{reclamationId}
    controller: App\Controller\ReclamationController::generatePdf
    methods: ['POST']

export_reclamations_excel:
    path: /reclamation/export/excel
    controller: App\Controller\ReclamationController::exportReclamationsExcel
