<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
=======

chat:
    path: /chat
    controller: App\Controller\ChatController::index
>>>>>>> 81688ff31e36db63b702e05ba73f5478ffdd725f
=======
#index:
#    path: /
#    controller: App\Controller\DefaultController::index

root_route_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /en
        permanent: true

home_page_en:
    path: Home/en
    controller: App\Controller\PanierController::index
    defaults:
        _locale: en

home_page_fr:
    path: Home/fr
    controller: App\Controller\PanierController::index
    defaults:
        _locale: fr
>>>>>>> 649ef9c620e35f87ee5e3746f7e798e948fc7cc4
=======
# index:
#    path: /
#    controller: App\Controller\DefaultController::index
reclamation:
  resource: App\Controller\ReclamationController
  type: annotation

add_reclamation_page:
    path: '/addReclamationPage'
    controller: 'App\Controller\ReclamationController::addReclamationPage'

    


reclamationDetails:
    path: /reclamation/{id}/details
    controller: App\Controller\ReclamationController::reclamationDetails
    requirements:
        id: '\d+'


reclamation_details:
    path: /reclamation/{id}
    controller: App\Controller\ReclamationController::reclamationDetails


repondre:
    resource: 'App\Controller\RepondreController'
    type:     annotation


generate_pdf:
    path: /generate-pdf/{reclamationId}
    controller: App\Controller\ReclamationController::generatePdf
    methods: ['POST']

export_reclamations_excel:
    path: /reclamation/export/excel
    controller: App\Controller\ReclamationController::exportReclamationsExcel
>>>>>>> 0f9be098c09a370d9b7246eec13ee77203b60875
=======
# index:
#    path: /
#    controller: App\Controller\DefaultController::index



calandrier:
    path: /calandrier
    controller: App\Controller\CalandrierController::index


# filter_gyms_by_address:
#     path: '/filter_gyms_by_address'
#     controller: App\Controller\GymController::filterGymsByAddress'
#     methods: ['GET']
>>>>>>> eb00ab66c5c8cb0c2ad54f78e46097d1f33bb681
